README.md

- Remove AB3 Details
- Add InnSync Details
- Add Acknowledgement

Update README.md for InnSync

---

README.md
docs/DeveloperGuide.md

Add use case for edit and find.
Add user stories.

Update developer guide

---

src/main/java/seedu/innsync/commons/util/StringUtil.java
src/main/java/seedu/innsync/logic/parser/ParserUtil.java
src/test/java/seedu/innsync/logic/parser/ParserUtilTest.java

Currently, consecutive spaces in the name and address fields will be kept.
With this PR, these consecutive spaces will be removed, adhering to the constraints set by the feature list.

Add Whitespace Parsing

---

src/main/java/seedu/innsync/logic/LogicManager.java
src/main/java/seedu/innsync/logic/commands/BookingTagCommand.java
src/main/java/seedu/innsync/logic/commands/DeleteCommand.java
src/main/java/seedu/innsync/logic/commands/EditCommand.java
src/main/java/seedu/innsync/logic/commands/FindCommand.java
src/main/java/seedu/innsync/logic/commands/StarCommand.java
src/main/java/seedu/innsync/model/Model.java
src/main/java/seedu/innsync/model/ModelManager.java
src/main/java/seedu/innsync/model/person/Name.java
src/test/java/seedu/innsync/logic/commands/AddCommandTest.java
src/test/java/seedu/innsync/logic/commands/CommandTestUtil.java
src/test/java/seedu/innsync/logic/commands/DeleteCommandTest.java
src/test/java/seedu/innsync/logic/commands/EditCommandTest.java
src/test/java/seedu/innsync/logic/commands/FindCommandTest.java
src/test/java/seedu/innsync/logic/commands/StarCommandTest.java
src/test/java/seedu/innsync/model/ModelManagerTest.java
src/test/java/seedu/innsync/testutil/TestUtil.java

- Sort contacts alphabetically among starred and non-starred
- star is no longer removed on addbt
- all operations to be performed only on sorted list

Fix Bugs for Star Command

---

src/main/java/seedu/innsync/logic/commands/UnstarCommand.java
src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
src/main/java/seedu/innsync/logic/parser/UnstarCommandParser.java
src/main/resources/view/PersonListCard.fxml

Implement unstar Command

---

src/main/java/seedu/innsync/model/tag/BookingTag.java
src/test/java/seedu/innsync/logic/commands/BookingTagCommandTest.java
src/test/java/seedu/innsync/logic/commands/CommandTestUtil.java

Also fixed bugs exposed by tests in BookingTag equals function

Add tests for BookingTagCommand

---

src/main/java/seedu/innsync/logic/commands/ListStarCommand.java
src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
src/main/java/seedu/innsync/model/Model.java

Implement liststar Command

---

src/main/java/seedu/innsync/logic/commands/TagCommand.java
src/main/java/seedu/innsync/logic/parser/TagCommandParser.java
src/test/java/seedu/innsync/logic/commands/CommandTestUtil.java
src/test/java/seedu/innsync/logic/commands/TagCommandTest.java

Fix tag command parsing to show the correct error messages

Fix issue #119

---

src/main/java/seedu/innsync/logic/commands/UntagCommand.java
src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java

Tag removal is still incomplete as current set is immutable.
@TanXingZhong please help to finish the implementation⭐️

Add incomplete untag command

---

src/main/java/seedu/innsync/logic/commands/UntagCommand.java
src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java

There still exists a bug where user can enter a empty tag when choosing the untag.
Please help fix @iuhiah : ⭐

Branch delete tag

---

src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java

Fix argument passing in untag command parser

---

src/test/java/seedu/innsync/logic/commands/ListStarCommandTest.java

Add tests for liststar

---

src/main/java/seedu/innsync/logic/commands/UntagCommand.java
src/test/java/seedu/innsync/logic/commands/UntagCommandTest.java
src/test/java/seedu/innsync/logic/parser/UntagCommandParserTest.java

Fixed bug in untag error message exposed by test (line 66 of `UntagCommand.java`)

Add tests for untag command and untag command parser

---

src/main/java/seedu/innsync/logic/parser/ParserUtil.java
src/main/java/seedu/innsync/model/person/Name.java
src/main/java/seedu/innsync/model/person/UniquePersonList.java
src/test/java/seedu/innsync/logic/commands/CommandTestUtil.java
src/test/java/seedu/innsync/logic/parser/ParserUtilTest.java
src/test/java/seedu/innsync/model/person/NameTest.java
src/test/java/seedu/innsync/storage/JsonAdaptedPersonTest.java

To give unique names that contains "/" use $ infront like $a/p

Allow unique names like X Æ A-Xii or a/p

---

src/main/java/seedu/innsync/logic/commands/ClearCommand.java
src/main/java/seedu/innsync/logic/commands/ConfirmCommand.java
src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
src/main/java/seedu/innsync/logic/parser/ClearCommandParser.java
src/main/java/seedu/innsync/logic/parser/ConfirmCommandParser.java
src/test/java/seedu/innsync/logic/commands/ClearCommandTest.java
src/test/java/seedu/innsync/logic/parser/AddressBookParserTest.java

Feature flaw
Before (clearing instantly clears the database)
Now (Y to confirm and else to cancel)

Add confirmation to clear

---

build.gradle
src/main/java/seedu/innsync/logic/commands/EditCommand.java
src/main/java/seedu/innsync/logic/commands/MarkRequestCommand.java
src/main/java/seedu/innsync/logic/commands/MemoCommand.java
src/main/java/seedu/innsync/logic/commands/RequestCommand.java
src/main/java/seedu/innsync/logic/parser/AddCommandParser.java
src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
src/main/java/seedu/innsync/logic/parser/EditCommandParser.java
src/main/java/seedu/innsync/logic/parser/MarkRequestCommandParser.java
src/main/java/seedu/innsync/logic/parser/ParserUtil.java
src/main/java/seedu/innsync/logic/parser/RequestCommandParser.java
src/main/java/seedu/innsync/model/AddressBook.java
src/main/java/seedu/innsync/model/ModelManager.java
src/main/java/seedu/innsync/model/person/Person.java
src/main/java/seedu/innsync/model/request/Request.java
src/main/java/seedu/innsync/model/util/SampleDataUtil.java
src/main/java/seedu/innsync/storage/JsonAdaptedBookingTag.java
src/main/java/seedu/innsync/storage/JsonAdaptedPerson.java
src/main/java/seedu/innsync/storage/JsonAdaptedRequest.java
src/main/java/seedu/innsync/ui/MainWindow.java
src/main/java/seedu/innsync/ui/PersonDetailPanel.java
src/main/resources/view/PersonDetailPanel.fxml
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/innsync/logic/commands/RequestCommandTest.java
src/test/java/seedu/innsync/logic/parser/RequestCommandParserTest.java
src/test/java/seedu/innsync/model/request/RequestTest.java
src/test/java/seedu/innsync/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/innsync/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/innsync/testutil/PersonBuilder.java
src/test/java/seedu/innsync/testutil/PersonUtil.java

- Implement Mark Request Command
- Change Requests field of Person to use List<> instead of Set<>
- Link Requests Checkbox UI to isComplete field
- Fix: Checking the Checkbox using the mouse also properly updates the Person isCompleted field

Implement Mark Request Command and Many Other Changes

---

src/test/java/seedu/innsync/logic/commands/CommandTestUtil.java
src/test/java/seedu/innsync/logic/commands/RequestCommandTest.java
src/test/java/seedu/innsync/logic/commands/UntagCommandTest.java
src/test/java/seedu/innsync/logic/parser/AddressBookParserTest.java
src/test/java/seedu/innsync/logic/parser/MarkCommandParserTest.java
src/test/java/seedu/innsync/logic/parser/RequestCommandParserTest.java
src/test/java/seedu/innsync/model/person/PersonTest.java
src/test/java/seedu/innsync/model/request/RequestTest.java
src/test/java/seedu/innsync/model/request/UniqueRequestListTest.java

MANY TEST CASES ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐

Add many test cases for parser command eta

---

src/main/java/seedu/innsync/logic/commands/DeleteRequestCommand.java
src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
src/main/java/seedu/innsync/logic/parser/DeleteRequestCommandParser.java
src/test/java/seedu/innsync/logic/commands/DeleteRequestCommandTest.java
src/test/java/seedu/innsync/logic/parser/DeleteRequestCommandParserTest.java

Add deletereq command

---

src/main/java/seedu/innsync/ui/PersonCard.java
src/main/java/seedu/innsync/ui/PersonDetailPanel.java
src/main/resources/view/LightTheme.css
src/main/resources/view/PersonDetailPanel.fxml
src/main/resources/view/PersonListCard.fxml

- remove mouse interaction on checkbox
- edit appearance of requests and memo UI

Modify Memo and Requests UI

---

docs/UserGuide.md

Remove listreq from the user guide

---

src/main/java/seedu/innsync/model/tag/BookingTag.java
src/test/java/seedu/innsync/model/tag/BookingTagTest.java

Add more date parse checks

---

docs/DeveloperGuide.md
docs/UserGuide.md

Fix typos in the User Guide and Developer Guide

---

src/main/java/seedu/innsync/logic/commands/UntagCommand.java
src/test/java/seedu/innsync/logic/commands/UntagCommandTest.java

Fix untag command messages

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/innsync/logic/parser/ParserUtil.java

Fixes #362 
Fixes #287 
Fixes #364

Add error handling for duplicate tags

---

src/main/java/seedu/innsync/logic/commands/DeleteRequestCommand.java
src/main/java/seedu/innsync/logic/commands/MarkRequestCommand.java
src/main/java/seedu/innsync/logic/commands/UnmarkRequestCommand.java
src/main/java/seedu/innsync/logic/parser/DeleteRequestCommandParser.java
src/main/java/seedu/innsync/logic/parser/MarkRequestCommandParser.java
src/main/java/seedu/innsync/logic/parser/UnmarkRequestCommandParser.java
src/test/java/seedu/innsync/logic/parser/DeleteRequestCommandParserTest.java
src/test/java/seedu/innsync/logic/parser/MarkRequestCommandParserTest.java
src/test/java/seedu/innsync/logic/parser/UnmarkRequestCommandParserTest.java

Fix error messages for request-related commands
